# Site settings
title: "AISF Trento"
description: "Sito del Comitato Locale di Trento"
url: "http://ai-sf.it/trento" # the base hostname & protocol for your site
destination: ../site/
locale: "it"

# Build settings
markdown: kramdown
future: true
permalink: /blog/:year/:month/:day/:title/
destination: _site


#facebook
fb_admins:
fb_appid:

#Collections
collections:
  events:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

plugins:
 - jekyll-redirect-from
 - jekyll-sitemap
